events {
    # Maximum number of connections NGINX can accept simultaneously (Default value)
    worker_connections 1024;
}

http {
    # Needed to properly recognize file types (CSS, JS, HTML)
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # 1. SSL/TLS Configuration (Project Rule: Only 443)
        listen 443 ssl;
        listen [::]:443 ssl; # IPv6 support

        # Point to the certificates we created in the Dockerfile
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Security Protocols (Project Rule: Only TLSv1.2 or TLSv1.3)
        ssl_protocols TLSv1.2 TLSv1.3;

        # 2. Domain Name and Root Directory
        server_name aozkaya.42.fr;
        root /var/www/html;
        index index.php index.html index.htm;

        # 3. Main Directory Configuration
        location / {
            # WordPress permalinks
            try_files $uri $uri/ /index.php?$args;
        }

        # 4. PHP File Processing (CRITICAL SECTION)
        # When a request ends with .php, forward it to WordPress
        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_index index.php;
            fastcgi_pass wordpress:9000;
        }
    }
}