secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    restart: always
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception_network
    volumes:
      - mariadb_vol:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    restart: always
    env_file: .env
    secrets:
      - db_password
      - credentials
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress_vol:/var/www/wordpress

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_vol:/var/www/wordpress

networks:
  inception_network:
    name: inception_network
    driver: bridge

volumes:
  mariadb_vol:
    name: mariadb_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aozkaya/data/mariadb
  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aozkaya/data/wordpress
