events {
    # NGINX'in aynı anda kaç bağlantı kabul edebileceği (Standart değer)
    worker_connections 1024;
}

http {
    # Dosya türlerini (CSS, JS, HTML) doğru tanıması için gerekli
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # 1. SSL/TLS Ayarları (Proje Kuralı: Sadece 443)
        listen 443 ssl;
        listen [::]:443 ssl; # IPv6 desteği için

        # Dockerfile'da oluşturduğumuz sertifikaları gösteriyoruz
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # Güvenlik Protokolleri (Proje Kuralı: Sadece TLSv1.2 veya TLSv1.3)
        ssl_protocols TLSv1.2 TLSv1.3;

        # 2. Alan Adı ve Kök Dizin
        server_name aozkaya.42.fr;
        root /var/www/html;
        index index.php index.html index.htm;

        # 3. Ana Dizin Ayarı
        location / {
            # İstenen dosya varsa aç, yoksa 404 ver
            try_files $uri $uri/ =404;
        }

        # 4. PHP Dosyalarını İşleme (EN KRİTİK KISIM)
        # Sonu .php ile biten bir istek gelirse bunu WordPress'e gönder
        location ~ \.php$ {
            # Dosya 404 ise PHP işlemcisine gönderme
            include snippets/fastcgi-php.conf;

            # WordPress servisine bağlan (Docker Compose servis ismi: wordpress)
            # 9000 portu, WordPress Dockerfile'ında açtığımız porttur.
            fastcgi_pass wordpress:9000;	
        }
    }
}