[server]

[mysqld]
user                    = mysql
pid-file                = /run/mysqld/mysqld.pid
socket                  = /run/mysqld/mysqld.sock
port                    = 3306
basedir                 = /usr
datadir                 = /var/lib/mysql
tmpdir                  = /tmp
lc-messages-dir         = /usr/share/mysql

# KRİTİK AYAR: Networking
# Varsayılan olarak bind-address 127.0.0.1'dir (Sadece Localhost).
# Bunu 0.0.0.0 yapıyoruz ki tüm ağlardan gelen istekleri kabul etsin.
bind-address            = 0.0.0.0

# Karakter seti (Emoji vs. desteği için utf8mb4 şart)
character-set-server    = utf8mb4
collation-server        = utf8mb4_general_ci

[embedded]

[mariadb]