services:
  nginx:
    build: ./srcs/nginx
    ports:
      - "443:443"
    networks:
      - inception-network
  
  wordpress:
    build: ./srcs/wordpress
    env_file:
      - .env
    networks:
      - inception-network

  mariadb:
    build: ./srcs/mariadb
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge
