services:
  nginx:
    build: ./srcs/nginx
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception-network
    # Your containers have to restart in case of a crash so I did this vvv
    restart: always
  
  wordpress:
    build: ./srcs/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always
    volumes:
      - wordpress_data:/var/www/html
  
  mariadb:
    build: ./srcs/mariadb
    env_file:
      - .env
    networks:
      - inception-network
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql

networks:
  inception-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aozkaya/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aozkaya/data/wordpress
