FROM debian:bookworm

RUN apt-get update && apt-get install -y \
		php8.2-fpm \
		php8.2-mysql \
		php8.2-curl \
		php8.2-mbstring \
		php8.2-xml \
		php8.2-zip \
		curl \
	&& rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
		-o /usr/local/bin/wp \
	&& chmod +x /usr/local/bin/wp

RUN mkdir -p /var/www/wordpress

COPY conf/www.conf    /etc/php/8.2/fpm/pool.d/www.conf
COPY tools/setup-wp.sh /setup-wp.sh
RUN  chmod +x /setup-wp.sh

EXPOSE 9000

ENTRYPOINT ["/setup-wp.sh"]
